# FlashAttention 3 sources, analysis modes, preparation, and binaries.

FA3_MK := $(lastword $(MAKEFILE_LIST))

HOPPER_FA3_DIR = $(HOPPER_SRC_DIR)/fa3
HOPPER_FA3_STANDARD_SOURCE = $(HOPPER_FA3_DIR)/fa3_fwd_hdim128_fp16_test.cc
HOPPER_FA3_STANDARD_OBJECT = $(OBJ_DIR)/hopper/fa3_standard/fa3_fwd_hdim128_fp16_test.cu.o

HOPPER_FA3_MODES = \
	baseline softmax_only qk_only pv_only qk_pv_only \
	tma_only tma_only_m3_only tma_only_first_round_bh \
	tma_only_first_round_bh_m3_only baseline_noprofile \
	softmax_only_noprofile qk_pv_only_noprofile base_no_tma \
	softmax_only_no_tma qk_pv_only_no_tma base_no_tma_noprofile \
	softmax_only_no_tma_noprofile qk_pv_only_no_tma_noprofile \
	qk_pv_only_no_tma_timeline qk_pv_only_no_tma_reg_timeline \
	sync_only_no_tma sync_only_no_tma_noprofile \
	qk_pv_only_no_tma_extended qk_pv_only_no_tma_extended_noprofile \
	qk_pv_only_no_tma_extended_reg_timeline
HOPPER_FA3_MODE_OBJECT = $(OBJ_DIR)/hopper/fa3_modes/$(1)/fa3_fwd_h1d128_profile_test.cu.o
HOPPER_FA3_MODE_OBJECTS = $(foreach mode,$(HOPPER_FA3_MODES),$(call HOPPER_FA3_MODE_OBJECT,$(mode)))

HOPPER_FA3_PREPARE_SCRIPT = $(HOPPER_FA3_DIR)/prepare_flash_attention.sh
HOPPER_FA3_PATCHES = $(wildcard $(HOPPER_FA3_DIR)/patches/*.patch)
HOPPER_FA3_PREPARED_STAMP = $(HOPPER_FA3_DIR)/flash-attention/.gpgpusim-prepared
HOPPER_FA3_GENERATED_HEADERS = \
	$(HOPPER_FA3_DIR)/flash-attention/hopper/flash_profile.h \
	$(HOPPER_FA3_DIR)/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp
HOPPER_FA3_PROFILE_HEADERS = \
	$(HOPPER_FA3_DIR)/fa3_fwd_hdim128_fp16_case.cuh \
	$(HOPPER_FA3_GENERATED_HEADERS)

HOPPER_FA3_COMMON_FLAGS = --ftemplate-backtrace-limit=0 -O3 \
                          --use_fast_math \
                          -lineinfo --expt-relaxed-constexpr \
                          --expt-extended-lambda \
                          -DCUTLASS_ENABLE_GDC_FOR_SM90 \
                          -DCUTLASS_DEBUG_TRACE_LEVEL=0 \
                          -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 \
                          -DCUTLASS_ARCH_MMA_SM90_SUPPORTED=1 \
                          -DNDEBUG \
                          -I$(HOPPER_FA3_DIR)/flash-attention/hopper \
                          -I$(HOPPER_FA3_DIR)/flash-attention/csrc/cutlass/include
HOPPER_FA3_EXTENDED_FLAGS = $(HOPPER_FA3_COMMON_FLAGS) -DCUTE_SM90_EXTENDED_MMA_SHAPES_ENABLED

HOPPER_FA3_STANDARD_TARGET = $(BIN_DIR)/hopper/run_fa3_standard_tests
HOPPER_FA3_MODE_TARGET = $(BIN_DIR)/hopper/run_fa3_$(1)_tests
HOPPER_FA3_MODE_TARGETS = $(foreach mode,$(HOPPER_FA3_MODES),$(call HOPPER_FA3_MODE_TARGET,$(mode)))

.PHONY: prepare-fa3-flash-attention fa3-standard fa3-modes

prepare-fa3-flash-attention: $(HOPPER_FA3_PREPARED_STAMP)

$(HOPPER_FA3_PREPARED_STAMP): $(HOPPER_FA3_PREPARE_SCRIPT) $(HOPPER_FA3_PATCHES)
	$(HOPPER_FA3_PREPARE_SCRIPT)
	@touch $@

$(HOPPER_FA3_GENERATED_HEADERS): $(HOPPER_FA3_PREPARED_STAMP)
	@test -f $@ || { echo "Prepared FlashAttention header is missing: $@" >&2; exit 1; }

fa3-standard: setup-gtest $(HOPPER_FA3_STANDARD_TARGET)

# Analysis groups reuse these mode binaries with different case lists.
fa3-modes: setup-gtest $(HOPPER_FA3_MODE_TARGETS)

define REGISTER_FA3_BUILD_TARGET
.PHONY: fa3-mode-$(1)
fa3-mode-$(1): setup-gtest $(call HOPPER_FA3_MODE_TARGET,$(1))
endef
$(foreach mode,$(HOPPER_FA3_MODES),$(eval $(call REGISTER_FA3_BUILD_TARGET,$(mode))))

$(HOPPER_FA3_STANDARD_OBJECT): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_EXTENDED_FLAGS)
$(HOPPER_FA3_STANDARD_OBJECT): $(HOPPER_FA3_STANDARD_SOURCE) \
$(CUH_HEADERS) $(TOP_MAKEFILE) $(FA3_MK) $(HOPPER_FA3_PREPARED_STAMP) | $(HOPPER_OBJ_DIR)
	@mkdir -p $(dir $@)
	$(NVCC) $(HOPPER_NVCCFLAGS) $(HOPPER_EXTRA_NVCCFLAGS) \
		$(INCLUDES) $(GPGPUSIM_FLAGS) -c $< -o $@

HOPPER_FA3_MODE_PROFILE_FLAGS = $(HOPPER_FA3_EXTENDED_FLAGS) -DFLASH_FWD_ENABLE_PROFILE_CLOCK -DFLASH_FWD_PROFILE_CLOCK_NON_ATOMIC -DFLASH_FWD_PROFILE_GLOBALTIMER -DFLASH_FWD_PROFILE_TASK_GLOBALTIMER
HOPPER_FA3_MODE_NOPROFILE_FLAGS = $(HOPPER_FA3_EXTENDED_FLAGS)
HOPPER_FA3_MODE_EXTENDED_PROFILE_FLAGS = $(HOPPER_FA3_EXTENDED_FLAGS) -DFLASH_FWD_ENABLE_PROFILE_CLOCK -DFLASH_FWD_PROFILE_CLOCK_NON_ATOMIC
HOPPER_FA3_MODE_EXTENDED_NOPROFILE_FLAGS = $(HOPPER_FA3_EXTENDED_FLAGS)
$(call HOPPER_FA3_MODE_OBJECT,baseline): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS)
$(call HOPPER_FA3_MODE_OBJECT,softmax_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA
$(call HOPPER_FA3_MODE_OBJECT,qk_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_PV_WGMMA
$(call HOPPER_FA3_MODE_OBJECT,pv_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_QK_WGMMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX
$(call HOPPER_FA3_MODE_OBJECT,tma_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX
$(call HOPPER_FA3_MODE_OBJECT,tma_only_m3_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_PROFILE_SCHED_M3_ONLY
$(call HOPPER_FA3_MODE_OBJECT,tma_only_first_round_bh): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_PROFILE_SCHED_FIRST_BH_SECTION_ONLY
$(call HOPPER_FA3_MODE_OBJECT,tma_only_first_round_bh_m3_only): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_PROFILE_SCHED_FIRST_BH_SECTION_ONLY -DFLASH_FWD_PROFILE_SCHED_M3_ONLY
$(call HOPPER_FA3_MODE_OBJECT,baseline_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS)
$(call HOPPER_FA3_MODE_OBJECT,softmax_only_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX
$(call HOPPER_FA3_MODE_OBJECT,base_no_tma): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,softmax_only_no_tma): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,base_no_tma_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,softmax_only_no_tma_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_timeline): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA -DFLASH_FWD_PROFILE_TIMELINE
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_reg_timeline): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA -DFLASH_FWD_PROFILE_REG_TIMELINE -DFLASH_FWD_PROFILE_REG_TIMELINE_ONLY
$(call HOPPER_FA3_MODE_OBJECT,sync_only_no_tma): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA -DFLASH_FWD_SENS_SYNC_ONLY
$(call HOPPER_FA3_MODE_OBJECT,sync_only_no_tma_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_QK_WGMMA -DFLASH_FWD_SENS_SKIP_PV_WGMMA -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA -DFLASH_FWD_SENS_SYNC_ONLY
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended): HOPPER_NVCCFLAGS = $(WGMMA_SM90A_NVCCFLAGS)
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_EXTENDED_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended_noprofile): HOPPER_NVCCFLAGS = $(WGMMA_SM90A_NVCCFLAGS)
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended_noprofile): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_EXTENDED_NOPROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended_reg_timeline): HOPPER_NVCCFLAGS = $(WGMMA_SM90A_NVCCFLAGS)
$(call HOPPER_FA3_MODE_OBJECT,qk_pv_only_no_tma_extended_reg_timeline): HOPPER_EXTRA_NVCCFLAGS = $(HOPPER_FA3_MODE_EXTENDED_PROFILE_FLAGS) -DFLASH_FWD_SENS_SKIP_SOFTMAX -DFLASH_FWD_SENS_SKIP_TMA -DFLASH_FWD_PROFILE_REG_TIMELINE -DFLASH_FWD_PROFILE_REG_TIMELINE_ONLY

$(HOPPER_FA3_MODE_OBJECTS): $(HOPPER_FA3_DIR)/fa3_fwd_h1d128_profile_test.cc \
$(CUH_HEADERS) $(HOPPER_FA3_PROFILE_HEADERS) $(TOP_MAKEFILE) $(FA3_MK) \
$(HOPPER_FA3_PREPARED_STAMP) | $(HOPPER_OBJ_DIR)
	@mkdir -p $(dir $@)
	$(NVCC) $(HOPPER_NVCCFLAGS) $(HOPPER_EXTRA_NVCCFLAGS) \
		$(INCLUDES) $(GPGPUSIM_FLAGS) -c $< -o $@

$(HOPPER_FA3_STANDARD_TARGET): $(HOPPER_FA3_STANDARD_OBJECT) \
$(OBJ_DIR)/gtest_main.a $(TOP_MAKEFILE) $(FA3_MK) | $(BIN_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(filter-out $(TOP_MAKEFILE) $(FA3_MK),$^) \
		-o $@ -lpthread $(CUDA_LIBS)

$(BIN_DIR)/hopper/run_fa3_%_tests: \
$(OBJ_DIR)/hopper/fa3_modes/%/fa3_fwd_h1d128_profile_test.cu.o \
$(OBJ_DIR)/gtest_main.a $(TOP_MAKEFILE) $(FA3_MK) | $(BIN_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(filter-out $(TOP_MAKEFILE) $(FA3_MK),$^) \
		-o $@ -lpthread $(CUDA_LIBS)
